"""Tests for galaxy, star system, and location generation."""

from data.names import LOCATION_TYPES, LOCATION_WORDS, SYSTEM_WORDS
from data.star_types import STAR_TYPES
from world.galaxy import Galaxy


def _explore_n(g, max_systems=15):
    """BFS-explore up to max_systems systems."""
    explored = set()
    queue = [g.home_system]
    while queue and len(explored) < max_systems:
        name = queue.pop(0)
        if name in explored:
            continue
        explored.add(name)
        g.arrive_at(name)
        for neighbor in g.systems[name].connections:
            if neighbor not in explored:
                queue.append(neighbor)


def test_home_system_exists_at_init():
    g = Galaxy(seed=1)
    assert g.home_system in g.systems
    assert g.current_system == g.home_system


def test_home_has_connections():
    g = Galaxy(seed=1)
    home = g.systems[g.home_system]
    assert len(home.connections) >= 2, "Home must have at least 2 exits"


def test_locations_generated():
    g = Galaxy(seed=1)
    for system in g.systems.values():
        assert len(system.locations) >= 2


def test_location_words_cover_all_types():
    for lt in LOCATION_TYPES:
        assert len(LOCATION_WORDS[lt]["adjectives"]) >= 20
        assert len(LOCATION_WORDS[lt]["nouns"]) >= 20


def test_enough_system_words():
    assert len(SYSTEM_WORDS["primaries"]) >= 20
    assert len(SYSTEM_WORDS["suffixes"]) >= 20


def test_location_names_are_unique_across_seeds():
    names = set()
    for seed in range(20):
        g = Galaxy(seed=seed)
        for system in g.systems.values():
            for loc in system.locations:
                names.add(loc.name)
    assert len(names) >= 30


def test_no_duplicate_names_within_galaxy():
    """All system and location names within a single galaxy must be unique."""
    for seed in range(50):
        g = Galaxy(seed=seed)
        _explore_n(g, 15)
        all_names: list[str] = []
        for sys in g.systems.values():
            all_names.append(sys.name)
            for loc in sys.locations:
                all_names.append(loc.name)
        dupes = [n for n in all_names if all_names.count(n) > 1]
        assert not dupes, f"seed={seed}: duplicate names {set(dupes)}"


def test_every_system_has_valid_star_type():
    for seed in range(10):
        g = Galaxy(seed=seed)
        for system in g.systems.values():
            assert hasattr(system, "star_type")
            assert system.star_type in STAR_TYPES, f"{system.name} has unknown star_type {system.star_type}"


def test_same_seed_produces_same_star_types():
    g1 = Galaxy(seed=42)
    g2 = Galaxy(seed=42)
    for name in g1.systems:
        assert g1.systems[name].star_type == g2.systems[name].star_type


def test_location_name_formats():
    """Names should be: adj+noun, noun only, or noun+number."""
    one_word = False
    two_word_alpha = False
    with_number = False
    for seed in range(50):
        g = Galaxy(seed=seed)
        _explore_n(g, 10)
        for system in g.systems.values():
            for loc in system.locations:
                parts = loc.name.split()
                if len(parts) == 1:
                    one_word = True
                elif len(parts) == 2 and parts[-1].isdigit():
                    with_number = True
                elif len(parts) == 2 and parts[-1].isalpha():
                    two_word_alpha = True
    assert one_word, "Expected some single-noun names"
    assert two_word_alpha, "Expected some adjective+noun names"
    assert with_number, "Expected some noun+number names"


def test_arrive_expands_frontier():
    """Arriving at a system should generate new connected systems."""
    g = Galaxy(seed=1)
    home = g.systems[g.home_system]
    neighbor_name = next(iter(home.connections))
    systems_before = len(g.systems)
    g.arrive_at(neighbor_name)
    # The neighbor should now have its frontier expanded (new systems generated)
    assert len(g.systems) >= systems_before


def test_arrive_idempotent():
    """Arriving at the same system twice should not change anything."""
    g = Galaxy(seed=1)
    home = g.systems[g.home_system]
    neighbor_name = next(iter(home.connections))
    g.arrive_at(neighbor_name)
    systems_after_first = dict(g.systems)
    connections_after_first = {n: dict(s.connections) for n, s in g.systems.items()}
    g.arrive_at(neighbor_name)
    assert set(g.systems.keys()) == set(systems_after_first.keys())
    for name in g.systems:
        assert g.systems[name].connections == connections_after_first[name]


def test_travel_cost_frontier_system():
    """travel_cost() returns 2 for a frontier (unexplored) system."""
    g = Galaxy(seed=1)
    home = g.systems[g.home_system]
    neighbor_name = next(iter(home.connections))
    # Neighbor was generated by home expansion but never arrived at -> frontier
    assert neighbor_name in g._unexplored_frontier
    assert g.travel_cost(neighbor_name) == 2


def test_travel_cost_explored_system():
    """travel_cost() returns 1 for an explored (visited) system."""
    g = Galaxy(seed=1)
    home = g.systems[g.home_system]
    neighbor_name = next(iter(home.connections))
    g.arrive_at(neighbor_name)
    # After arriving, it's no longer frontier
    assert neighbor_name not in g._unexplored_frontier
    assert g.travel_cost(neighbor_name) == 1


def test_unique_location_name_fallback():
    """Fallback path must not raise when all simple attempts collide."""
    import random as _random

    from world.galaxy import _unique_location_name

    rng = _random.Random(0)
    type_words = {"adjectives": ["Old"], "nouns": ["Hulk"]}
    used: set[str] = set()
    # Fill up the obvious names so the fallback fires
    used.add("Old Hulk")
    used.add("Hulk")
    for i in range(2, 1000):
        used.add(f"Hulk {i}")
    name = _unique_location_name(rng, type_words, used, max_attempts=0)
    assert name not in used - {name}, "returned name should be unique"


def test_dreadnought_name_reserved():
    """The Dreadnought system name must never be generated for a regular system."""
    from world.galaxy import DREADNOUGHT_SYSTEM_NAME

    for seed in range(100):
        g = Galaxy(seed=seed)
        _explore_n(g, 20)
        for name, sys in g.systems.items():
            if name == DREADNOUGHT_SYSTEM_NAME:
                # Only valid if it was explicitly spawned
                assert g.dreadnought_system == name
